# Тестовые данные
 GET http://localhost:3123/api HTTP/1.1
Content-Type: application/json
###
#Предложения
## Получить список предложений
  GET http://localhost:4390/offer HTTP/1.1
Content-Type: application/json
###
